# with Create React App, we need to make a small modification:

# script:
#   - docker run USERNAME/docker-react npm run test -- --coverage
 
# instead should be:

# script:
#   - docker run -e CI=true USERNAME/docker-react npm run test
# Additionally, you may want to set the following property to the top of your .travis.yml file:

# language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t ms642/docker-react -f Dockerfile.dev .

script: # default behaviour is to check when the test exists and other than 0 equals fail
  - docker run -e CI=true ms642/docker-react npm run test