#docker-compose down && docker-compose up --build || docker-compose up --build
version: '3'
services: 
  web:
    build:
      context: . # Tell it where to look for for the files
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    # second service for tests
  tests:
    build:
      context: . # Tell it where to look for for the files
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    environment:
        - CHOKIDAR_USEPOLLING=true
